logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot:
          autoconfigure: ERROR
    com:
      chatapp:
        backend: INFO
server:
  port: 3001

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import:





